name: Build

on: [push, pull_request]

jobs:
  build-windows:
    name: Build Windows Executable
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: casdoor
          MYSQL_ROOT_PASSWORD: 123456
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '^1.16.5'
          cache-dependency-path: ./go.mod

      - name: Build for Windows
        run: |
          GOOS=windows GOARCH=amd64 go build -o casdoor.exe
        working-directory: ./

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: casdoor-windows
          path: ./casdoor.exe
